### ISSUE TITLE
上架Chrome商店

### ISSUE THREAD

**Issue by StrollStars** [AnthonyJu/webext-minimalism-extension-manager#1]
请问会上架Chrome应用商店吗？

**Comment by AnthonyJu** [comment]
考虑中，一个月内出

**Comment by AnthonyJu** [comment]
> 考虑中，一个月内出

支付劝退😂

**Comment by StrollStars** [comment]
> > 考虑中，一个月内出
> 
> 支付劝退😂

上架还要钱？

**Comment by AnthonyJu** [comment]
虽说只有5美刀，可是它需要境外银行卡，懒得鼓捣了，鼓捣不明白再被弄去缅北噶腰子😂

**Comment by AnthonyJu** [comment]
> > > 考虑中，一个月内出
> > 
> > 
> > 支付劝退😂
> 
> 上架还要钱？

虽说只有5美刀，可是它需要境外银行卡，懒得鼓捣了，鼓捣不明白再被弄去缅北噶腰子😂

**Comment by StrollStars** [comment]
确实门槛也太高了，先谢过开发者了。
