### ISSUE TITLE
功能上的好奇與希望

### ISSUE THREAD

**Issue by KamiyaMinoru** [AnthonyJu/webext-minimalism-extension-manager#2]
好奇為什麼不能像原生的管理器一樣將擴充放到工具列
那有沒有可能改成加一顆按鈕來呼叫原生管理器
就可以不用讓它一起佔著一個工具列空間了

另請問
有可能除了排序也開發分組功能嗎
不然套件多了其實有點亂
希望能折疊一些起來
(有的管理器則是讓使用者可以隱藏一些平常不會去調整的擴充)

**Comment by AnthonyJu** [comment]
“什麼不能像原生的管理器一樣將擴充放到工具列”、“加一顆按鈕來呼叫原生管理器”：浏览器未提供相关API，插件使用说明中写了哈

分組功能可以考虑后续加上

**Comment by AnthonyJu** [comment]
分组功能有咯

**Comment by KamiyaMinoru** [comment]
> 分组功能有咯

期待改版上架(已經看到edge的介紹圖有這功能了
