### ISSUE TITLE
每次重启浏览器就会打开设置页面

### ISSUE THREAD

**Issue by ghost** [AnthonyJu/webext-minimalism-extension-manager#3]
win11 22631.2861
edge 122.0.2365.66

每次重启浏览器就会打开设置页面
![image](https://github.com/AnthonyJu/webext-minimalism-extension-manager/assets/45709525/81948b4d-9507-4ba3-96b3-ae44babd78b7)

怎么能设置不打开呢？

**Comment by AnthonyJu** [comment]
将在下个版本中修复（预计两周左右）

**Comment by AnthonyJu** [comment]
修复啦

**Comment by ghost** [comment]
👍
