### ISSUE TITLE
已經刪掉的套件還會留在列表上

### ISSUE THREAD

**Issue by KamiyaMinoru** [AnthonyJu/webext-minimalism-extension-manager#4]
發現bug, 如圖:
![image](https://github.com/AnthonyJu/webext-minimalism-extension-manager/assets/78710607/11d895e7-0dc0-4c76-9272-1a899c8f72ca)

**Comment by AnthonyJu** [comment]
收到🫡

**Comment by KamiyaMinoru** [comment]
補充: 我發現卡到這個bug以後 新安裝的套件也不會出現在列表了

**Comment by AnthonyJu** [comment]
是的，这两个一样的问题，我的测试代码，忘记删除了😭，不过修复了，已经提交，在 In review 了😬

**Comment by AnthonyJu** [comment]
> 補充: 我發現卡到這個bug以後 新安裝的套件也不會出現在列表了

可以在新发布的版本中看一下效果了🤪
