### ISSUE TITLE
關於排版

### ISSUE THREAD

**Issue by KamiyaMinoru** [AnthonyJu/webext-minimalism-extension-manager#6]
![image](https://github.com/AnthonyJu/webext-minimalism-extension-manager/assets/78710607/6386653d-56c5-4a62-91c9-a2359ac9b649)

![image](https://github.com/AnthonyJu/webext-minimalism-extension-manager/assets/78710607/76b9d5f8-db65-46ed-aae4-7e7623a781ca)

如圖:插件裝多了在分組的時候會有點操作障礙 這方面不曉得未來是不是有可能看怎麼調整

**Comment by AnthonyJu** [comment]
会在后续的优化中增加滚动😊

**Comment by AnthonyJu** [comment]
> 会在后续的优化中增加滚动😊

完成
