### ISSUE TITLE
看不到的擴展 unable to see extensions when the list of the group is too long

### ISSUE THREAD

**Issue by KamiyaMinoru** [AnthonyJu/webext-minimalism-extension-manager#7]
擴展裝太多的話會看不到 導致無法分組 如圖

![image](https://github.com/AnthonyJu/webext-minimalism-extension-manager/assets/78710607/260e7b73-8faf-44de-bc27-baa1dea2b794)

**Comment by AnthonyJu** [comment]
在下个版本中修复，已在 In review
